//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 color palettes.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 0 files.
  struct file {
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 20 images.
  struct image {
    /// Image `Beth`.
    static let beth = Rswift.ImageResource(bundle: R.hostingBundle, name: "Beth")
    /// Image `Brent`.
    static let brent = Rswift.ImageResource(bundle: R.hostingBundle, name: "Brent")
    /// Image `Carter`.
    static let carter = Rswift.ImageResource(bundle: R.hostingBundle, name: "Carter")
    /// Image `Chris`.
    static let chris = Rswift.ImageResource(bundle: R.hostingBundle, name: "Chris")
    /// Image `Dale`.
    static let dale = Rswift.ImageResource(bundle: R.hostingBundle, name: "Dale")
    /// Image `Darrell`.
    static let darrell = Rswift.ImageResource(bundle: R.hostingBundle, name: "Darrell")
    /// Image `Dave`.
    static let dave = Rswift.ImageResource(bundle: R.hostingBundle, name: "Dave")
    /// Image `Glen`.
    static let glen = Rswift.ImageResource(bundle: R.hostingBundle, name: "Glen")
    /// Image `Jean`.
    static let jean = Rswift.ImageResource(bundle: R.hostingBundle, name: "Jean")
    /// Image `Joy`.
    static let joy = Rswift.ImageResource(bundle: R.hostingBundle, name: "Joy")
    /// Image `June`.
    static let june = Rswift.ImageResource(bundle: R.hostingBundle, name: "June")
    /// Image `Kent`.
    static let kent = Rswift.ImageResource(bundle: R.hostingBundle, name: "Kent")
    /// Image `Kyle`.
    static let kyle = Rswift.ImageResource(bundle: R.hostingBundle, name: "Kyle")
    /// Image `Lester`.
    static let lester = Rswift.ImageResource(bundle: R.hostingBundle, name: "Lester")
    /// Image `Linda`.
    static let linda = Rswift.ImageResource(bundle: R.hostingBundle, name: "Linda")
    /// Image `Melvin`.
    static let melvin = Rswift.ImageResource(bundle: R.hostingBundle, name: "Melvin")
    /// Image `Oscar`.
    static let oscar = Rswift.ImageResource(bundle: R.hostingBundle, name: "Oscar")
    /// Image `Peggy`.
    static let peggy = Rswift.ImageResource(bundle: R.hostingBundle, name: "Peggy")
    /// Image `Ruby`.
    static let ruby = Rswift.ImageResource(bundle: R.hostingBundle, name: "Ruby")
    /// Image `Zoe`.
    static let zoe = Rswift.ImageResource(bundle: R.hostingBundle, name: "Zoe")
    
    /// `UIImage(named: "Beth", bundle: ..., traitCollection: ...)`
    static func beth(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.beth, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Brent", bundle: ..., traitCollection: ...)`
    static func brent(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.brent, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Carter", bundle: ..., traitCollection: ...)`
    static func carter(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.carter, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Chris", bundle: ..., traitCollection: ...)`
    static func chris(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.chris, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Dale", bundle: ..., traitCollection: ...)`
    static func dale(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.dale, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Darrell", bundle: ..., traitCollection: ...)`
    static func darrell(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.darrell, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Dave", bundle: ..., traitCollection: ...)`
    static func dave(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.dave, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Glen", bundle: ..., traitCollection: ...)`
    static func glen(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.glen, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Jean", bundle: ..., traitCollection: ...)`
    static func jean(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.jean, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Joy", bundle: ..., traitCollection: ...)`
    static func joy(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.joy, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "June", bundle: ..., traitCollection: ...)`
    static func june(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.june, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Kent", bundle: ..., traitCollection: ...)`
    static func kent(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.kent, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Kyle", bundle: ..., traitCollection: ...)`
    static func kyle(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.kyle, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Lester", bundle: ..., traitCollection: ...)`
    static func lester(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.lester, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Linda", bundle: ..., traitCollection: ...)`
    static func linda(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.linda, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Melvin", bundle: ..., traitCollection: ...)`
    static func melvin(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.melvin, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Oscar", bundle: ..., traitCollection: ...)`
    static func oscar(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.oscar, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Peggy", bundle: ..., traitCollection: ...)`
    static func peggy(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.peggy, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Ruby", bundle: ..., traitCollection: ...)`
    static func ruby(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.ruby, compatibleWith: traitCollection)
    }
    
    /// `UIImage(named: "Zoe", bundle: ..., traitCollection: ...)`
    static func zoe(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.zoe, compatibleWith: traitCollection)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 0 nibs.
  struct nib {
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 13 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `ImageCollectionTableViewCell`.
    static let imageCollectionTableViewCell: Rswift.ReuseIdentifier<ImageCollectionTableViewCell> = Rswift.ReuseIdentifier(identifier: "ImageCollectionTableViewCell")
    /// Reuse identifier `ParticipantsCell`.
    static let participantsCell: Rswift.ReuseIdentifier<ReactiveTableViewCell> = Rswift.ReuseIdentifier(identifier: "ParticipantsCell")
    /// Reuse identifier `RemindCell`.
    static let remindCell: Rswift.ReuseIdentifier<ReactiveTableViewCell> = Rswift.ReuseIdentifier(identifier: "RemindCell")
    /// Reuse identifier `ScheduleBellTableViewCell`.
    static let scheduleBellTableViewCell: Rswift.ReuseIdentifier<ScheduleBellTableViewCell> = Rswift.ReuseIdentifier(identifier: "ScheduleBellTableViewCell")
    /// Reuse identifier `ScheduleNoteTableViewCell`.
    static let scheduleNoteTableViewCell: Rswift.ReuseIdentifier<ScheduleNoteTableViewCell> = Rswift.ReuseIdentifier(identifier: "ScheduleNoteTableViewCell")
    /// Reuse identifier `ScheduleParticipantItemCollectionViewCell`.
    static let scheduleParticipantItemCollectionViewCell: Rswift.ReuseIdentifier<ScheduleParticipantItemCollectionViewCell> = Rswift.ReuseIdentifier(identifier: "ScheduleParticipantItemCollectionViewCell")
    /// Reuse identifier `ScheduleParticipantTableViewCell`.
    static let scheduleParticipantTableViewCell: Rswift.ReuseIdentifier<ScheduleParticipantTableViewCell> = Rswift.ReuseIdentifier(identifier: "ScheduleParticipantTableViewCell")
    /// Reuse identifier `ScheduleRemindTableViewCell`.
    static let scheduleRemindTableViewCell: Rswift.ReuseIdentifier<ScheduleRemindTableViewCell> = Rswift.ReuseIdentifier(identifier: "ScheduleRemindTableViewCell")
    /// Reuse identifier `ScheduleTextInputTableViewCell`.
    static let scheduleTextInputTableViewCell: Rswift.ReuseIdentifier<ScheduleTextInputTableViewCell> = Rswift.ReuseIdentifier(identifier: "ScheduleTextInputTableViewCell")
    /// Reuse identifier `ScheduleTextTableViewCell`.
    static let scheduleTextTableViewCell: Rswift.ReuseIdentifier<ScheduleTextTableViewCell> = Rswift.ReuseIdentifier(identifier: "ScheduleTextTableViewCell")
    /// Reuse identifier `ScheduleTimePickerTableViewCell`.
    static let scheduleTimePickerTableViewCell: Rswift.ReuseIdentifier<ScheduleTimePickerTableViewCell> = Rswift.ReuseIdentifier(identifier: "ScheduleTimePickerTableViewCell")
    /// Reuse identifier `ScheduleTimeTableViewCell`.
    static let scheduleTimeTableViewCell: Rswift.ReuseIdentifier<ScheduleTimeTableViewCell> = Rswift.ReuseIdentifier(identifier: "ScheduleTimeTableViewCell")
    /// Reuse identifier `SelectImageCollectionViewCell`.
    static let selectImageCollectionViewCell: Rswift.ReuseIdentifier<SelectImageCollectionViewCell> = Rswift.ReuseIdentifier(identifier: "SelectImageCollectionViewCell")
    
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 3 view controllers.
  struct segue {
    /// This struct is generated for `ImageCollectionListViewController`, and contains static references to 1 segues.
    struct imageCollectionListViewController {
      /// Segue identifier `showSelectImages`.
      static let showSelectImages: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, ImageCollectionListViewController, SelectImagesViewController> = Rswift.StoryboardSegueIdentifier(identifier: "showSelectImages")
      
      /// Optionally returns a typed version of segue `showSelectImages`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func showSelectImages(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, ImageCollectionListViewController, SelectImagesViewController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.imageCollectionListViewController.showSelectImages, segue: segue)
      }
      
      fileprivate init() {}
    }
    
    /// This struct is generated for `NewScheduleViewController`, and contains static references to 1 segues.
    struct newScheduleViewController {
      /// Segue identifier `changeRemind`.
      static let changeRemind: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, NewScheduleViewController, ScheduleRemindViewController> = Rswift.StoryboardSegueIdentifier(identifier: "changeRemind")
      
      /// Optionally returns a typed version of segue `changeRemind`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func changeRemind(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, NewScheduleViewController, ScheduleRemindViewController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.newScheduleViewController.changeRemind, segue: segue)
      }
      
      fileprivate init() {}
    }
    
    /// This struct is generated for `SelectImagesViewController`, and contains static references to 1 segues.
    struct selectImagesViewController {
      /// Segue identifier `showSelectImageDetail`.
      static let showSelectImageDetail: Rswift.StoryboardSegueIdentifier<UIKit.UIStoryboardSegue, SelectImagesViewController, SelectImageDetailViewController> = Rswift.StoryboardSegueIdentifier(identifier: "showSelectImageDetail")
      
      /// Optionally returns a typed version of segue `showSelectImageDetail`.
      /// Returns nil if either the segue identifier, the source, destination, or segue types don't match.
      /// For use inside `prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)`.
      static func showSelectImageDetail(segue: UIKit.UIStoryboardSegue) -> Rswift.TypedStoryboardSegueInfo<UIKit.UIStoryboardSegue, SelectImagesViewController, SelectImageDetailViewController>? {
        return Rswift.TypedStoryboardSegueInfo(segueIdentifier: R.segue.selectImagesViewController.showSelectImageDetail, segue: segue)
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 2 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Main`.
    static let main = _R.storyboard.main()
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Main", bundle: ...)`
    static func main(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.main)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 0 localization tables.
  struct string {
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct nib {
    fileprivate init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try main.validate()
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      fileprivate init() {}
    }
    
    struct main: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UINavigationController
      
      let bundle = R.hostingBundle
      let name = "Main"
      let scheduleAddParticipantsViewController = StoryboardViewControllerResource<ScheduleAddParticipantsViewController>(identifier: "ScheduleAddParticipantsViewController")
      let scheduleDeleteParticipantsViewController = StoryboardViewControllerResource<ScheduleDeleteParticipantsViewController>(identifier: "ScheduleDeleteParticipantsViewController")
      let scheduleNoteViewController = StoryboardViewControllerResource<ScheduleNoteViewController>(identifier: "ScheduleNoteViewController")
      let scheduleRemindViewController = StoryboardViewControllerResource<ScheduleRemindViewController>(identifier: "ScheduleRemindViewController")
      
      func scheduleAddParticipantsViewController(_: Void = ()) -> ScheduleAddParticipantsViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: scheduleAddParticipantsViewController)
      }
      
      func scheduleDeleteParticipantsViewController(_: Void = ()) -> ScheduleDeleteParticipantsViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: scheduleDeleteParticipantsViewController)
      }
      
      func scheduleNoteViewController(_: Void = ()) -> ScheduleNoteViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: scheduleNoteViewController)
      }
      
      func scheduleRemindViewController(_: Void = ()) -> ScheduleRemindViewController? {
        return UIKit.UIStoryboard(resource: self).instantiateViewController(withResource: scheduleRemindViewController)
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "avatar") == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'avatar' is used in storyboard 'Main', but couldn't be loaded.") }
        if _R.storyboard.main().scheduleDeleteParticipantsViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'scheduleDeleteParticipantsViewController' could not be loaded from storyboard 'Main' as 'ScheduleDeleteParticipantsViewController'.") }
        if _R.storyboard.main().scheduleNoteViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'scheduleNoteViewController' could not be loaded from storyboard 'Main' as 'ScheduleNoteViewController'.") }
        if _R.storyboard.main().scheduleAddParticipantsViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'scheduleAddParticipantsViewController' could not be loaded from storyboard 'Main' as 'ScheduleAddParticipantsViewController'.") }
        if _R.storyboard.main().scheduleRemindViewController() == nil { throw Rswift.ValidationError(description:"[R.swift] ViewController with identifier 'scheduleRemindViewController' could not be loaded from storyboard 'Main' as 'ScheduleRemindViewController'.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}